[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

board_build.f_cpu = 600000000L
board_build.usbtype = USB_MIDI_SERIAL

build_flags =
    -D USB_MIDI_SERIAL
    -D TEENSY_OPT_FASTER

lib_deps =
    PaulStoffregen/ILI9341_t3
    PaulStoffregen/XPT2046_Touchscreen

lib_ldf_mode = deep+
monitor_speed = 115200
